### ISSUE TITLE
Poloniex: returnOpenOrders:  pair = all, returns all info except symbols/pairs

### ISSUE THREAD

**Issue by Akroni** [jjxtra/ExchangeSharp#182]
I have a [BUG REPORT] or [FEATURE REQUEST]

Details:

Hi, when we are trying to retrieve all open orders via returnOpenOrders, at the poloniex api.
We do get all seperate order details, except the symbol/pair. 

Error Logs (if any):

[Method] = POST
[ProtocolVersion] = 1.1
[Proxy] = System.Net.WebRequest+WebProxyWrapper
[ReadWriteTimeout] = 30000
[Referer] = 
[RequestUri] = https://poloniex.com/tradingApi
[Timeout] = 30000
12-6-2018 14:21:02Start of Payload
Key : nonce : value : 636644028621705700
Key : command : value : returnOpenOrders
Key : currencyPair : value : all

**Comment by jjxtra** [comment]
Fixed in ab35a37cd27b69879470edf0792df20969a61f46. Donations are always appreciated :)

**Comment by Akroni** [comment]
I admire the extremely fast reponse however it is not resolved. Poloniex has the odd habit of grouping the responses for this api call by coin in the following format. 

{"BTC_1CR":[],"BTC_AC":[{"orderNumber":"120466","type":"sell","rate":"0.025","amount":"100","total":"2.5"},{"orderNumber":"120467","type":"sell","rate":"0.04","amount":"100","total":"4"}],

**Comment by jjxtra** [comment]
Try it now

**Comment by Akroni** [comment]
Got it to work
